CREATE OR REPLACE TABLE STG.STAGING.STG_DISTANCE (
	"Id_Distance" NUMBER(2,0),
	"Lib_Distance" VARCHAR(50),
	"Desc_Distance" VARCHAR(50),
    CONSTRAINT SRC_REFDISTANCE_PK PRIMARY KEY ("Id_Distance")
);

TRUNCATE TABLE stg_distance;